name: iv_project_api_core
description: "IV Project Api Core"
version: 0.0.4
homepage:
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  iv_project_core:
    path: ../iv_project_core

  dio: ^5.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
